# Generated by Django 4.2.16 on 2024-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_name_script_script_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
