# Generated by Django 4.2.16 on 2024-09-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_script_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='content',
            field=models.TextField(),
        ),
    ]
