# Generated by Django 4.2.16 on 2024-09-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_script_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='delete_script',
            field=models.BooleanField(default=False),
        ),
    ]
